# Generated by Django 5.0.1 on 2024-01-29 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("Employee_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("First_Name", models.CharField(max_length=50)),
                ("Last_Name", models.CharField(max_length=50)),
                ("Address", models.CharField(max_length=255)),
                ("Phone_Number", models.CharField(max_length=15)),
                ("Email_Address", models.EmailField(max_length=100)),
                ("Joining_Date", models.DateField()),
                ("Job_Level", models.CharField(max_length=50)),
                ("Is_Remote_Employee", models.BooleanField()),
                ("Job_Description", models.CharField(max_length=100)),
                ("Designation", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("Project_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Project_Name", models.CharField(max_length=100)),
                ("Is_Live", models.BooleanField()),
                ("Description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("Skill_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Skill_Name", models.CharField(max_length=50)),
                ("Skill_Proficiency", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Chat_History",
            fields=[
                ("Chat_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Message", models.TextField()),
                ("Response", models.TextField()),
                ("Timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "Employee_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="botservice.employee",
                    ),
                ),
                (
                    "Receiver_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="botservice.employee",
                    ),
                ),
                (
                    "Sender_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="botservice.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emp_Project",
            fields=[
                (
                    "Emp_Project_ID",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("Role", models.CharField(max_length=50)),
                (
                    "Employee_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="botservice.employee",
                    ),
                ),
                (
                    "Project_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="botservice.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emp_Skill",
            fields=[
                (
                    "Emp_Skill_ID",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "Employee_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="botservice.employee",
                    ),
                ),
                (
                    "Skill_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="botservice.skill",
                    ),
                ),
            ],
        ),
    ]
