# Generated by Django 5.0.1 on 2024-01-29 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("botservice", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat_history",
            old_name="Chat_ID",
            new_name="ID",
        ),
        migrations.RenameField(
            model_name="emp_project",
            old_name="Emp_Project_ID",
            new_name="ID",
        ),
        migrations.RenameField(
            model_name="emp_skill",
            old_name="Emp_Skill_ID",
            new_name="ID",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="Employee_ID",
            new_name="ID",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="Project_ID",
            new_name="ID",
        ),
        migrations.RenameField(
            model_name="skill",
            old_name="Skill_ID",
            new_name="ID",
        ),
        migrations.RemoveField(
            model_name="chat_history",
            name="Receiver_ID",
        ),
        migrations.RemoveField(
            model_name="chat_history",
            name="Sender_ID",
        ),
    ]
