# Generated by Django 5.0.1 on 2024-01-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botservice", "0002_rename_chat_id_chat_history_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="Skill_Proficiency",
        ),
        migrations.AddField(
            model_name="emp_skill",
            name="Skill_Proficiency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="chat_history",
            name="ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="emp_project",
            name="ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="emp_skill",
            name="ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="skill",
            name="ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
