# Generated by Django 5.0.1 on 2024-01-30 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botservice", "0003_remove_skill_skill_proficiency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat_history",
            name="Employee_ID",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="botservice.employee",
            ),
        ),
    ]
